version: "3.9"

services:
  app1:
    build:
      context: ./my-images1
      dockerfile: ../Dockerfile
    container_name: app1
    # ports:
    #   - "8001:8000"

  app2:
    build:
      context: ./my-images2
      dockerfile: ../Dockerfile
    container_name: app2
    # ports:
    #   - "8002:8000"

  app3:
    build:
      context: ./my-images3
      dockerfile: ../Dockerfile
    container_name: app3
    # ports:
    #   - "8003:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
